[target.'cfg(target_os = "linux")']
rustflags = [
"-Clink-arg=-Wl,--export-dynamic-symbol=custom_labels_abi_version",
"-Clink-arg=-Wl,--export-dynamic-symbol=custom_labels_current_set",
"-Clink-arg=-Wl,--export-dynamic-symbol=otel_thread_ctx_v1",
]